#HalfminerBot default config
#Server to connect to
host: 'yourhost.com'
#Default port is 9987
ports:
  #The servers voice port (the one you use when connecting to it via the client)
  serverPort: 9987
  #Server query port, default is 10011
  queryPort: 10011
#Can also be provided via command line, as "java -jar HalfminerBot.jar password"
password: ''
#Bot name on the server (query clients are not visible in tree view)
botName: 'Halfminer TSBot'
#Channel to join
botChannelName: 'Welcome'
command:
  channelcreate:
    #Delay in seconds until a channel will be deleted after the last client leaves
    channelDeleteDelay: 180
    #Channel group to add the player to
    channelGroupAdminID: 2
