#HalfminerBot configuration
#Server address to connect to, can also be an IP address
host: 'yourhost.com'
ports:
  #The servers voice port (the one you use when connecting to it via the client)
  serverPort: 9987
  #Server query port, default is 10011
  queryPort: 10011
credentials:
  #Query user to login as
  username: 'serveradmin'
  #Can also be provided via command line, as "java -jar HalfminerBot.jar password"
  password: ''
#Bot name on the server (query clients are not visible in tree view, will be name in chat)
botName: 'Halfminer TSBot'
#Channel the bot will be joining and using as base channel for commands
botChannelName: 'Welcome'
command:
  channelcreate:
    #Delay in seconds until a channel will be deleted after the last client leaves
    channelDeleteDelay: 180
    #Channel group to add the player to
    channelGroupAdminID: 2
task:
  settings:
    #Provide three arguments per task seperated by comma
    # First:    number  initial execution delay
    # Seconds:  number  delay between subsequent execution
    # Third:    unit    time unit for first and second argument, example: disabled, seconds, minutes, hours, ...
    Inactivity: 10, 10, seconds
    ReloadConfig: 20, 20, seconds
    Status: 0, 2, disabled
  inactivity:
    #String the designated AFK channel must contain, channels necessary talk power must also be higher than 0
    channelNameContains: 'AFK'
    #How many clients to kick from AFK lounge when server is full
    clientsToKickIfFull: 2
    #Time in seconds until users will be marked inactive (only if speakers are muted), marking as AFK overrides this
    idleTimeUntilMove: 300
groups:
  #key is group name (can be changed) and value is talk power.
  #You can add as many groups as you like, but they cannot have the same talk power
  admin: 100
  moderator: 50
  default: 0
#Hand out permission nodes to groups. Higher groups inherit lower groups permissions
permissions:
  admin:
  - cmd.stop
  moderator:
  - task.inactivity.exempt.move
  - task.inactivity.exempt.kick
  default:
  - cmd.channelcreate
